# Generated by Django 5.0.1 on 2024-01-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Dislikes',
            new_name='dislikes',
        ),
    ]
